package net.andreu.ajuntaments;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;
import javafx.stage.FileChooser;
import javafx.stage.FileChooser.ExtensionFilter;

public class SampleController implements Initializable {
	@FXML
	private ComboBox<String> cbxAjuntament;
	@FXML
	private Button btnCarregar;
	@FXML
	private Button btnSortir;

	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

	}

	// Event Listener on ComboBox[#cbxAjuntament].onAction
	@FXML
	public void ConsultarDades(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnCarregar].onMouseClicked
	@FXML
	public void CarregaDades(MouseEvent event) {

		FileChooser buscador = new FileChooser();
		buscador.getExtensionFilters().addAll(new ExtensionFilter("CSV Files", "*.csv"));
		File selectedFile = buscador.showOpenDialog(null);

		if (selectedFile != null) {
			
		}
	}

	// Event Listener on Button[#btnSortir].onMouseClicked
	@FXML
	public void Sortir(MouseEvent event) {
		Platform.exit();
	}
}
